name: library_base
description: library base package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.7+2
  cookie_jar: ^1.0.1
  date_format: ^1.0.8
  event_bus: ^1.1.1
  path_provider: ^1.6.8
  package_info: ^0.4.0+18
  permission_handler: ^5.0.0+hotfix.5
  encrypt: ^4.1.0
  flutter_easyrefresh: ^2.1.8
  extended_nested_scroll_view: ^2.0.0
  flutter_spinkit: ^4.1.2+1
  umeng_analytics_plugin: ^1.0.3
  lpinyin: ^1.1.0
  image_picker: ^0.6.7+14
  image_cropper: ^1.3.1
  image_gallery_saver: ^1.6.6
  photo_view: ^0.10.2
  fl_chart: ^0.12.0
  flutter_echarts: ^1.4.0
  flutter_bugly: ^0.3.0+2
  flutter_xupdate: ^1.0.0
  qr_flutter: ^3.1.0
  share: ^0.6.5+4
  fluwx: ^2.5.0+1
  decimal: ^0.3.5
  web_socket_channel: ^1.1.0

  flutter_inappwebview: ^4.0.0+4
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^1.0.6
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.2.0+1
  # 网络库 https://github.com/flutterchina/dio
  dio: ^3.0.9
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^4.3.2+2
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.3.2
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^5.4.7
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^1.7.3
  # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.3.1+1
  # 列表悬浮头 https://github.com/fluttercommunity/flutter_sticky_headers
  sticky_headers: ^0.1.8+1
  # 极光推送 https://github.com/jpush/jpush-flutter-plugin
  jpush_flutter: 0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/

flutter_intl:
  enabled: true
