name: library_base
description: library base package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  dokit: ^0.2.12
  # https://github.com/flutter/plugins/tree/master/packages/shared_preferences
  shared_preferences: ^0.5.12+4
  #日期格式化 https://github.com/tejainece/date_format
  date_format: ^1.0.9
  # https://github.com/marcojakob/dart-event-bus
  event_bus: ^1.1.1
  # https://github.com/flutter/plugins/tree/master/packages/path_provider
  path_provider: ^1.6.8
  # https://github.com/flutter/plugins/tree/master/packages/package_info
  package_info: ^0.4.0+18
  # https://github.com/Baseflow/flutter-permission-handler
  permission_handler: ^5.1.0+2
  # 加密库 https://github.com/leocavalcante/encrypt
  encrypt: ^4.1.0
  # 下拉刷新上拉加载 https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: ^1.6.4
  # 扩展NestedScrollView https://github.com/fluttercandies/extended_nested_scroll_view
  # extended_nested_scroll_view: ^2.0.1-dev
  # loading动画 https://github.com/jogboms/flutter_spinkit
  flutter_spinkit: ^5.0.0
  # 友盟统计 https://github.com/flmn/umeng_analytics_plugin
  umeng_analytics_plugin: ^1.0.3
  # 汉字转拼音 https://github.com/flutterchina/lpinyin
  lpinyin: ^1.1.1
  # 图片选择插件 https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: ^0.6.7+14
  # 图片裁剪 https://github.com/hnvn/flutter_image_cropper
  image_cropper: ^1.3.1
  # 图片保存至相册 https://github.com/hui-z/image_gallery_saver
  image_gallery_saver: ^1.6.8
  # 图片手势缩放（看大图）https://github.com/fireslime/photo_view
  photo_view: ^0.10.3
  # 图表库 https://github.com/imaNNeoFighT/fl_chart
  fl_chart: ^0.20.1
  # 基于echart的图表库 https://github.com/entronad/flutter_echarts
  flutter_echarts: ^1.5.0
  # bugly https://github.com/crazecoder/flutter_bugly
  flutter_bugly: ^0.3.0+2
  # app更新 https://github.com/xuexiangjys/flutter_xupdate
  flutter_xupdate: ^1.0.2
  # 二维码 https://github.com/theyakka/qr.flutter
  qr_flutter: ^3.2.0
  # 分享 https://github.com/flutter/plugins/tree/master/packages/share
  share: ^0.6.5+4
  # 微信SDK插件 https://github.com/OpenFlutter/fluwx
  fluwx: ^2.6.2
  # 小数计算 https://github.com/a14n/dart-decimal
  decimal: ^1.0.0
  # https://github.com/dart-lang/web_socket_channel
  web_socket_channel: ^1.1.0
  # 更强大的webview插件 https://github.com/pichillilorenzo/flutter_inappwebview
  flutter_inappwebview: ^4.0.0+4
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^1.0.7
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.5.0
  # 网络库 https://github.com/flutterchina/dio
  dio: ^3.0.10
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^5.0.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.0.0
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^5.4.7
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^2.0.3
  # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.3.1+1
  # 列表悬浮头 https://github.com/fluttercommunity/flutter_sticky_headers
  sticky_headers: ^0.1.8+1
  # 极光推送 https://github.com/jpush/jpush-flutter-plugin
  # jpush_flutter: 0.6.3
  # https://github.com/avioli/uni_links/tree/master/uni_links
  uni_links: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/

flutter_intl:
  enabled: true
